### ISSUE TITLE
IllegalStateException: Couldn't read row 545, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly be...

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1091]
### Description

Sentry Issue: [POCKET-CASTS-ANDROID-2PN](https://a8c.sentry.io/issues/3715459562/?referrer=github_integration)

```
IllegalStateException: Couldn't read row 545, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
    at android.database.CursorWindow.getLong(CursorWindow.java:539)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
    at au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl$43.call(EpisodeDao_Impl.java:7086)
    at au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl$43.call(EpisodeDao_Impl.java:0)
...
(10 additional frame(s) were not displayed)
```

Zendesk: 6388780-zd-woothemes

### Step-by-step reproduction instructions

Unable to reproduce so far, seems like it happens occasionally when there are new episodes in a podcast and the podcast is updated.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by ashiagr** [comment]
This exception occurs while trying to fetch a primitive (long) value from the `Cursor` for the field `size_in_bytes`:

<img width="686" alt="Screenshot 2023-06-16 at 12 08 53 PM" src="https://github.com/Automattic/pocket-casts-android/assets/1405144/44e060b7-1ea2-4118-bf08-4feb64739997">

Android Cursor documentation for `getLong`  method:


```
    /**
     * Returns the value of the requested column as a long.
     *
     * <p>The result and whether this method throws an exception when the
     * column value is null, the column type is not an integral type, or the
     * integer value is outside the range [<code>Long.MIN_VALUE</code>,
     * <code>Long.MAX_VALUE</code>] is implementation-defined.
     *
     * @param columnIndex the zero-based index of the target column.
     * @return the value of that column as a long.
     */
    long getLong(@IntRange(from = 0) int columnIndex);
```


Checked that the field is declared `NOT NULL` [here](https://github.com/Automattic/pocket-casts-android/blob/f4e962a3a49daf48d1df68a4eda9c45258cbdf0c/modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt#L107).

**Comment by rezzap** [comment]
New report from the user in 6416917-zd-woothemes

Podcast it happened on: https://pca.st/podcast/3189e570-25ad-012e-057a-00163e1b201c

They mentioned it happening just before sending the new tickets to us with the logs. 

> I just switched to the podcast.
I didn't even listen to it.

```
I 16/6 13:01:38 Observing podcast 3189e570-25ad-012e-057a-00163e1b201c episode changes
E 16/6 13:01:39 Fatal crash.
java.lang.IllegalStateException: Couldn't read row 661, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:539)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
	at da.g$i0.a(EpisodeDao_Impl.java:382)
	at da.g$i0.call(EpisodeDao_Impl.java:1)
	at go.i.u(MaybeFromCallable.java:16)
	at un.l.a(Maybe.java:15)
	at fo.n$a.onNext(FlowableFlatMapMaybe.java:37)
	at fo.y$c.c(FlowableObserveOn.java:40)
	at fo.y$a.run(FlowableObserveOn.java:18)
	at lo.d$c$a.run(ExecutorScheduler.java:11)
	at lo.d$c.run(ExecutorScheduler.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

I 16/6 13:03:36 App started. 7.39.1 (9102)
I 16/6 13:03:37 Set up periodic refresh
I 16/6 13:03:37 Playback service created
I 16/6 13:04:00 Set up periodic refresh
```

**Comment by mchowning** [comment]
There don't appear to be very many of these kinds of events in Sentry at all recently, but I did see one [in a recent release](https://a8c.sentry.io/issues/4686902956/?end=2023-12-20T01%3A58%3A59&project=6711064&query=+IllegalStateException&referrer=issue-stream&sort=freq&start=2023-12-08T15%3A00%3A00&stream_index=20) (`7.53-rc-2`), so although I think we might be able to close this, I'll leave it open to give some more time to assess how often this is happening.
