### ISSUE TITLE
Playback: App becomes unresponsive in some cases

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#1556]
### Description

We've got a report that the Android app becomes unresponsive when playing episodes in Pocket Casts. The Android app not freezing but when it gets in this error state the play control is non-responsive. The customer experiences the problem once a day, especially after listening to a different audio source. They also mentioned that the issue occurs even though episodes are downloaded, not streamed, and only happens with Pocket Casts. 

Workaround: Killing Pocket Casts from the task switcher and the mini player from the notification area, then relaunching the app. The play button then works.

We said it could be related to https://github.com/androidx/media/issues/23

Logs: 

<details>

```
E 08/11 09:05:42 Play failed.
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at i5.t1.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecDecoderException: Decoder failed: c2.sec.mp3.decoder
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.e0(SourceFile:3)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.s(SourceFile:154)
	at i5.t1.q(SourceFile:97)
	at i5.t1.handleMessage(SourceFile:223)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2672)
	at o5.e.g(SourceFile:8)
	at o5.e.f(SourceFile:71)
	at o5.e.a(SourceFile:1)
	at o5.e$a.handleMessage(SourceFile:3)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 3 more

E 08/11 09:05:42 Player error MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
I 08/11 09:05:42 Stopping playback
```

Slack thread: p1699519367670219-slack-C02A333D8LQ
Tickets: 
7278254-zd-a8c
7327506-zd-a8c

### Step-by-step reproduction instructions

1. Listen to a podcast using a Bluetooth headset
2. Connect your phone to your cars Bluetooth and attempt to resume playback

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App version : 7.52-rc-2 (9162)
Phone: samsung - Galaxy S21 Ultra 5G - SM-G998U - p3q
Android version: 13 SDK 33

**Comment by igotdes** [comment]
We have new logs from the user in #7335772-zen. The episode to check is `Saw X with Kevin Greutert and Marcus Dunstan (Ep. 446)`. The relevant portions of the log seem to be the following:

<details>
<summary>Details</summary>

```
I 20/11 09:04:19 Play 0.000 System Player. Saw X with Kevin Greutert and Marcus Dunstan (Ep. 446) Downloaded: true, Downloading: false, Audio: true, File: http://chrt.fm/track/G1746E/http://feeds.soundcloud.com/stream/1667901402-thedirectorscut-saw-x-with-kevin-greutert-and-marcus-dunstan-ep-446.mp3, EpisodeUuid: 49dc3e33-ac08-4d8f-97ed-281ec0441682, PodcastUuid: 55c77df0-84f4-0133-2d8b-6dc413d6d41d
I 20/11 09:04:19 startForeground state: 3
I 20/11 09:04:19 startForeground state: 3
E 20/11 09:04:19 Play failed.
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at i5.t1.handleMessage(SourceFile:359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecDecoderException: Decoder failed: c2.sec.mp3.decoder
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.e0(SourceFile:3)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.s(SourceFile:154)
	at i5.t1.q(SourceFile:97)
	at i5.t1.handleMessage(SourceFile:223)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2672)
	at o5.e.g(SourceFile:8)
	at o5.e.f(SourceFile:71)
	at o5.e.a(SourceFile:1)
	at o5.e$a.handleMessage(SourceFile:3)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 3 more

E 20/11 09:04:19 Player error MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
I 20/11 09:04:19 Stopping playback
```
</details>

I also asked them if they have only observed the issue when using Bluetooth. They said, so far, yes, although they also very rarely listen without Bluetooth.
