### ISSUE TITLE
Fatal crash on App start due to large bitmap

### ISSUE THREAD

**Issue by darkmattercoder** [Automattic/pocket-casts-android#1664]
### Description

Today while I was rearranging my play queue, suddenly the app closed. Subsequent start attempts lead to instant closing of the app. I cleared the cache, forced app stop and reopened but the issue persisted. 

I then managed to make the app stay open by turning on airplane mode on my phone. When Airplane mode is on, I can start playing from the UI and all is fine as long as pocket casts is in the background. Even turning off the airplane mode did not crash the app.

However when data connection is available again, as soon as I put the UI in the foreground, it crashes again. After confirming that I can get access to the app by turning data connections off and clearing the cache, I managed to get the log entry of a failed start attempt. 

The Log states that the crash happened due to an attempt to draw a too large bitmap file. The log states that the bitmap in question has  around 136MB. However, I cannot see from the log, which podcast or episode is causing this.

I would expect that pocketcasts catches such an exception and does not display a too large bitmap instead of crashing. I don't care when such an apparently too large bitmap is not displayed.

Here is the respective log:

```
03/1 21:45:07 App started. 7.54-rc-5 (9179)
I 03/1 21:45:07 Set up periodic refresh
I 03/1 21:45:07 Playback service created
E 03/1 21:45:08 Fatal crash.
java.lang.RuntimeException: Canvas: trying to draw too large(136142224bytes) bitmap.
at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
at ig.b.draw(SourceFile:136)
at android.widget.ImageView.onDraw(ImageView.java:1446)
at android.view.View.draw(View.java:23900)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
at android.view.View.draw(View.java:23903)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.draw(View.java:23903)
at androidx.core.widget.NestedScrollView.draw(SourceFile:1)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at androidx.recyclerview.widget.RecyclerView.drawChild(SourceFile:1)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.draw(View.java:23903)
at androidx.recyclerview.widget.RecyclerView.draw(SourceFile:1)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:136)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.draw(View.java:23903)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.draw(View.java:23903)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:136)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.updateDisplayListIfDirty(View.java:22758)
at android.view.View.draw(View.java:23631)
at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
at android.view.View.draw(View.java:23903)
at com.android.internal.policy.DecorView.draw(DecorView.java:809)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:5144)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4835)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4011)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8194)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
 

### Step-by-step reproduction instructions

1. open app
2. see app crash
(I don't think that you can reproduce this exactly, because it depends on an episode picture apparently)

### Screenshots or screen recording

no need to add a screen recording of an app which closes itself immediately

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

`Google Pixel 8` with `android 14`, pocket casts `7.54-rc-5 (9179)`

**Comment by ashiagr** [comment]
Fixed in `7.55-rc-2`
