### ISSUE TITLE
Crash on episode archive -> deletion

### ISSUE THREAD

**Issue by jeremywohl** [Automattic/pocket-casts-android#573]
### Description

Something in the archive -> deletion path is causing a reliable crash. For all but one podcast, I have delete-on-archive set -- and these always crash the app -- but this one podcast does not. So deletion appears to be the focus.

However, there are instances where I've manually archived a downloaded podcast, and these did not crash the app. But it's not consistent.

Further, "un-downloading" (but not archiving) a downloaded podcast does _not_ crash the app.

### Step-by-step reproduction instructions

Listen to a podcast to completion, or during listen use any of the mark-as-played paths, or archive a downloaded episode from any list with a swipe, crash.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 5, Android 13, Pocket Casts 7.25.

**Comment by jeremywohl** [comment]
Thoughts?

**Comment by mchowning** [comment]
👋  @jeremywohl ! Thanks for reporting this. Unfortunately, I haven't been able to reproduce it.

> I have delete-on-archive set 

That's the app's default behavior, right? Or maybe I'm misunderstanding what you mean. 

If we are talking about the default behavior, I would expect that we would have gotten a lot of bug reports about this since, as you are very aware, this would be very frustrating. I'm not aware of any other reports of this though. 🤔 

Has the app always done this for you, or did it work fine for a while before it started crashing? 

Could you reach out to support with the app's logs from shortly after one of these crashes? The app's logs will be attached automatically if you reach out to support via `Profile` → ⚙️ → `Help & Feedback` → `Get in Touch`.

**Comment by jeremywohl** [comment]
I've been using pocketcasts for years, but this crashing behavior only presented in the past 6mos.

I've submitted the debug log through support.

Here's the relevant bit:

```
E 10/12 23:48:16 Fatal crash.
java.lang.RuntimeException: LiveData does not handle errors. Errors from publishers should be handled upstream and propagated as state
	at androidx.lifecycle.z$b$a$a.run(LiveDataReactiveStreams.java:7)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: Couldn't read row 561, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:539)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
	at q7.g$k0.a(EpisodeDao_Impl.java:382)
	at q7.g$k0.call(EpisodeDao_Impl.java:1)
	at xl.i.u(MaybeFromCallable.java:16)
	at ll.l.b(Maybe.java:15)
	at wl.m$a.onNext(FlowableFlatMapMaybe.java:37)
	at wl.x$c.f(FlowableObserveOn.java:40)
	at wl.x$a.run(FlowableObserveOn.java:18)
	at cm.d$c$a.run(ExecutorScheduler.java:11)
	at cm.d$c.run(ExecutorScheduler.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by azollafox** [comment]
The full logs sent can be found in 5787683-zen

**Comment by jeremywohl** [comment]
To narrow the issue, it only seems to occur when on, or branching from, the Downloads view.

**Comment by mchowning** [comment]
> it only seems to occur when on, or branching from, the Downloads view.

Thanks for the additional info. I still can't seem to reproduce this though, unfortunately. 😞 

I do see other reports with similar stacktraces [in our crash reports](https://a8c.sentry.io/share/issue/1230fde63e44432b860f80a5c822b701/), so you're the only one seeing this. 

The app's database could be in a bad state. Have you uninstalled and reinstalled the app since this started happening? If you have and that didn't fix the issue, then that would probably rule out database corruption.

**Comment by jeremywohl** [comment]
For posterity, my workaround has been to create a Downloaded filter page, and operate from there -- without crashing.

But I accept that this could be data corruption, and will close this issue.

Thanks.
